# The base accumulo image to use for all components.
imagePullPolicy: Always
externalAccess:
  enabled: false
  service:
    type: NodePort
    nodePorts: # The nodePorts list must match the number of manager replicas in the deployment
    - 30995
    - 30996
s3:
  bucket: "accumulo"
  key:
  secret: 
  token: 
  endpoint: https://s3.us-east-2.amazonaws.com
  path_style_access: 
  ssl_enabled: true
ingress:
  enabled: false
  dn: "mydn.com"
  path: /
proxy:
  image: public.ecr.aws/o1d3y8h1/accumulo-proxy:2.1.0
  enabled: false
accumulo:
  image: public.ecr.aws/o1d3y8h1/accumulo-s3:2.1.0
  # run the init script on startup
  init: false
  gc:
    resources:
      requests:
        memory: "500Mi"
        cpu: 0.5
    javaOpts:
      memory: "'-Xmx385m' '-Xms385m'"
  manager:
    replicas: 2
    resources:
      requests:
        memory: "5Gi"
        cpu: 2
    javaOpts:
      memory: "'-Xmx4g' '-Xms4g'"
  monitor:
    resources:
      requests:
        memory: "1Gi"
        cpu: 1
    javaOpts:
      memory: "'-Xmx768m' '-Xms768m'"
  tserver:
    replicas: 3
    resources:
      requests:
        memory: "2Gi"
        cpu: 2
    javaOpts:
      memory: "'-Xmx1536m' '-Xms1536m'"
  proxy:
    replicas: 1
  username: "root"
  passwd: "root"
  instance_name: "test"

zookeeper:
  host: "zookeeper-0.zookeeper-headless.accumulo.svc.cluster.local:2181,zookeeper-1.zookeeper-headless.accumulo.svc.cluster.local:2181,zookeeper-2.zookeeper-headless.accumulo.svc.cluster.local:2181"
  port: 2181
  containerPort: 2888
  electionPort: 3888
  replicas: 3
