# The base accumulo image to use for all components.
accumuloImage: public.ecr.aws/o1d3y8h1/accumulo-s3:s3a
imagePullPolicy: Always

# Select anitAffinity as either hard or soft, default is hard
antiAffinity: "soft"

s3:
  bucket: "accumulo"
  key:
  secret:
#  endpoint:
#  region:

accumulo:
  # run the init script on startup
  init: false
  gc:
    resources:
      requests:
        memory: "500Mi"
        cpu: 0.5
    javaOpts:
      memory: "'-Xmx385m' '-Xms385m'"
  manager:
    replicas: 1
    resources:
      requests:
        memory: "5Gi"
        cpu: 2
    javaOpts:
      memory: "'-Xmx4g' '-Xms4g'"
  monitor:
    resources:
      requests:
        memory: "1Gi"
        cpu: 1
    javaOpts:
      memory: "'-Xmx768m' '-Xms768m'"
  tserver:
    replicas: 5
    resources:
      requests:
        memory: "2Gi"
        cpu: 2
    javaOpts:
      memory: "'-Xmx1536m' '-Xms1536m'"
  volumes: "s3a://accumulo/accumulo,s3a://accumulo/accumulo-wal"
  username: "root"
  passwd: "root"
  instance_name: "s3"

zookeeper:
  host: zookeeper-0.zookeeper-headless.accumulo.svc.cluster.local,zookeeper-1.zookeeper-headless.accumulo.svc.cluster.local,zookeeper-2.zookeeper-headless.accumulo.svc.cluster.local
  port: 2181
  containerPort: 2888
  electionPort: 3888
  replicas: 3
