# The base accumulo image to use for all components.
accumuloImage: public.ecr.aws/o1d3y8h1/accumulo-s3:2.1.0
imagePullPolicy: Always

externalAccess:
  enabled: false
  service:
    type: NodePort
    nodePorts: # The nodePorts list must match the number of manager replicas in the deployment
    - 30995
    - 30996
s3:
  bucket: "accumulo"
  key:
  secret: 
  token: 
  endpoint:
  path_style_access: 
  ssl_enabled: true
ingress:
  enabled: false
  dn:
  path: /
accumulo:
  # run the init script on startup
  init: false
  gc:
    resources:
      requests:
        memory: "500Mi"
        cpu: 0.5
    javaOpts:
      memory: "'-Xmx385m' '-Xms385m'"
  manager:
    replicas: 2
    resources:
      requests:
        memory: "5Gi"
        cpu: 2
    javaOpts:
      memory: "'-Xmx4g' '-Xms4g'"
  monitor:
    resources:
      requests:
        memory: "1Gi"
        cpu: 1
    javaOpts:
      memory: "'-Xmx768m' '-Xms768m'"
  tserver:
    replicas: 5
    resources:
      requests:
        memory: "2Gi"
        cpu: 2
    javaOpts:
      memory: "'-Xmx1536m' '-Xms1536m'"
  username: "root"
  passwd: "root"
  instance_name: "s3"

zookeeper:
  host: zookeeper
  port: 2181
  containerPort: 2888
  electionPort: 3888
  replicas: 3
