apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "accumulo.fullname" . }}-manager-pdb
  labels:
    app: {{ template "accumulo.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: accumulo-manager
spec:
  selector:
    matchLabels:
      app: {{ template "accumulo.name" . }}
      release: {{ .Release.Name }}
      component: accumulo-manager
  minAvailable: 1 # FIXME: HA?