# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ template "accumulo.fullname" . }}-ts-svc
  labels:
    app: {{ template "accumulo.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: accumulo-ts
spec:
  clusterIP: "None"
  ports:
    - name: tablet-server
      protocol: TCP
      port: 9997
      targetPort: 9997
    - name: tablet-replication
      protocol: TCP
      port: 10002
      targetPort: 10002
    - name: monitor-centralized-logs
      protocol: TCP
      port: 4560
      targetPort: 4560
  selector:
    app: {{ template "accumulo.name" . }}
    component: accumulo-ts