apiVersion: v1
kind: Secret
metadata:
  name: {{ template "accumulo.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  s3-key: {{ print .Values.s3.key | b64enc | quote }}
  s3-secret: {{ print .Values.s3.secret | b64enc | quote }}
  s3-token: {{ print .Values.s3.token | b64enc | quote }}
  accumulo-root-user: {{ print .Values.accumulo.passwd | b64enc | quote }}
  accumulo-root-passwd: {{ print .Values.accumulo.username | b64enc | quote }}  # Base64-encoded value of "password"
  accumulo-instance-secret: {{ print .Values.accumulo.instance_secret | b64enc | quote }}