{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
Kind: Ingress
metadata:
  name: {{ template "accumulo.fullname" . }}-ingress
spec:
  rules:
    - host: {{ template "accumulo.fullname" . }}.{{ .Values.ingress.dn }}
      http:
        paths:
        - path: {{ .Values.ingress.path }}
          pathType: Prefix
          backend:
            service:
              name: {{ template "accumulo.fullname" . }}-manager-svc
              port:
                number: 9995
{{- end -}}