apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "accumulo.fullname" . }}-wal-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /{{ .Values.s3.bucket }}/accumulo-wal
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "accumulo.fullname" . }}-wal-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi