apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "accumulo.fullname" . }}-gc
  labels:
    app: {{ template "accumulo.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: accumulo-gc
spec:
  selector:
    matchLabels:
      app: {{ template "accumulo.name" . }}
  serviceName: {{ template "accumulo.fullname" . }}-gc-svc
  replicas: {{ .Values.accumulo.gc.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "accumulo.name" . }}
        release: {{ .Release.Name }}
        component: accumulo-gc
    spec:
      dnsConfig:
        searches:
        - {{ template "accumulo.fullname" . }}-gc-svc.accumulo.svc.cluster.local
        - {{ template "accumulo.fullname" . }}-monitor-svc.accumulo.svc.cluster.local
        - {{ template "accumulo.fullname" . }}-manager-svc.accumulo.svc.cluster.local
        - {{ template "accumulo.fullname" . }}-ts-svc.accumulo.svc.cluster.local
      affinity:
      terminationGracePeriodSeconds: 0
      containers:
      - name: accumulo-gc
        image: {{ .Values.accumuloImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: AWS_ACCESS_KEY_ID
          value: {{ .Values.s3.key }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ .Values.s3.secret }}
        command:
        - "/bin/bash"
        - "/tmp/accumulo-config/bootstrap.sh"
        resources:
{{ toYaml .Values.accumulo.gc.resources | indent 10 }}
#        readinessProbe:
#          httpGet:
#            path: /
#            port: 9999
#          initialDelaySeconds: 5
#          timeoutSeconds: 2
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 9999
#          initialDelaySeconds: 10
#          timeoutSeconds: 2
        volumeMounts:
        - name: accumulo-config
          mountPath: /tmp/accumulo-config
      volumes:
      - name: accumulo-config
        configMap:
          name: accumulo-configmap