apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "accumulo.fullname" . }}-ts
  labels:
    app: {{ template "accumulo.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: accumulo-ts
spec:
  selector:
    matchLabels:
      app: {{ template "accumulo.name" . }}
  serviceName: {{ template "accumulo.fullname" . }}-ts-svc
  replicas: {{ .Values.accumulo.tserver.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "accumulo.name" . }}
        release: {{ .Release.Name }}
        component: accumulo-ts
    spec:
      terminationGracePeriodSeconds: 60
      initContainers:
      - name: accumulo-ts-wait
        image: {{ .Values.accumulo.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
        - "/bin/bash"
        - "/tmp/accumulo-config/ts-wait.sh"
        resources:
          requests:
            memory: 256Mi
            cpu: 0.5
        volumeMounts:
        - name: accumulo-config
          mountPath: /tmp/accumulo-config
        - name: s3a-buffer
          mountPath: /s3a
      containers:
      - name: accumulo-ts
        image: {{ .Values.accumulo.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: AWS_ACCESS_KEY_ID
          value: {{ .Values.s3.key }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ .Values.s3.secret }}
        command:
        - "/bin/bash"
        - "/tmp/accumulo-config/tserver.sh"
        livenessProbe:
          tcpSocket:
            port: 9997
          initialDelaySeconds: 30
          periodSeconds: 5
        lifecycle:
          preStop:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "/tmp/accumulo-config/tserver-shutdown.sh > /proc/1/fd/1"
        resources:
{{ toYaml .Values.accumulo.tserver.resources | indent 10 }}
        volumeMounts:
        - name: accumulo-config
          mountPath: /tmp/accumulo-config
        - name: s3a-buffer
          mountPath: /s3a
      volumes:
      - name: accumulo-config
        configMap:
          name: accumulo-configmap
          defaultMode: 0777
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: component
                      operator: In
                      values:
                        - {{ template "accumulo.fullname" . }}-ts
                topologyKey: kubernetes.io/hostname
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: {{ .Values.accumulo.tserver.tolerations.not_ready }}
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: {{ .Values.accumulo.tserver.tolerations.unreachable }}
  volumeClaimTemplates:
  - metadata:
      name: s3a-buffer
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.accumulo.tserver.buffer.storageClass.name }}
      resources:
        requests:
          storage: {{ .Values.accumulo.tserver.buffer.size }}
      volumeMode: Filesystem