{{- $name := include "accumulo.name" . }}
{{- $fullName := include "accumulo.fullname" . }}
{{- $replicaCount := .Values.accumulo.tserver.replicas | int }}
{{- $root := . }}

{{- range $i, $e := until $replicaCount }}
{{- $targetName := printf "%s-ts-%d" (printf "%s" $fullName) $i }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $targetName }}
spec:
  ports:
    - name: tablet-server
      protocol: TCP
      port: 9997
      targetPort: 9997
    - name: tablet-replication
      protocol: TCP
      port: 10002
      targetPort: 10002
  selector:
    statefulset.kubernetes.io/pod-name: {{ $targetName }}
---
{{- end }}